/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppHandoversRouteImport } from './routes/_app.handovers'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppSubscriptionsRouteImport } from './routes/_app.subscriptions'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as HuddleChannelIdRouteImport } from './routes/huddle.$channelId'
import { Route as AppAgentsIndexRouteImport } from './routes/_app.agents.index'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'
import { Route as AppAgentsNewRouteImport } from './routes/_app.agents.new'
import { Route as AppCChannelIdRouteImport } from './routes/_app.c.$channelId'
import { Route as AppDmChannelIdRouteImport } from './routes/_app.dm.$channelId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppSettingsLinearRouteImport } from './routes/_app.settings.linear'
import { Route as AppSettingsRepositoriesRouteImport } from './routes/_app.settings.repositories'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth.invite.$token'
import { Route as AppChannelsChannelIdSettingsRouteImport } from './routes/_app.channels.$channelId.settings'
import { Route as AppDepartmentsDepartmentIdSettingsRouteImport } from './routes/_app.departments.$departmentId.settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoversRoute = AppHandoversRouteImport.update({
  id: '/handovers',
  path: '/handovers',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const HuddleChannelIdRoute = HuddleChannelIdRouteImport.update({
  id: '/huddle/$channelId',
  path: '/huddle/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsNewRoute = AppAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCChannelIdRoute = AppCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmChannelIdRoute = AppDmChannelIdRouteImport.update({
  id: '/dm/$channelId',
  path: '/dm/$channelId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLinearRoute = AppSettingsLinearRouteImport.update({
  id: '/settings/linear',
  path: '/settings/linear',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRepositoriesRoute = AppSettingsRepositoriesRouteImport.update({
  id: '/settings/repositories',
  path: '/settings/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppChannelsChannelIdSettingsRoute =
  AppChannelsChannelIdSettingsRouteImport.update({
    id: '/channels/$channelId/settings',
    path: '/channels/$channelId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppDepartmentsDepartmentIdSettingsRoute =
  AppDepartmentsDepartmentIdSettingsRouteImport.update({
    id: '/departments/$departmentId/settings',
    path: '/departments/$departmentId/settings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/handovers': typeof AppHandoversRoute
  '/members': typeof AppMembersRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tasks': typeof AppTasksRoute
  '/vault': typeof AppVaultRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/signup': typeof AuthSignupRoute
  '/huddle/$channelId': typeof HuddleChannelIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/c/$channelId': typeof AppCChannelIdRoute
  '/dm/$channelId': typeof AppDmChannelIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/linear': typeof AppSettingsLinearRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/departments/$departmentId/settings': typeof AppDepartmentsDepartmentIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/handovers': typeof AppHandoversRoute
  '/members': typeof AppMembersRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tasks': typeof AppTasksRoute
  '/vault': typeof AppVaultRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/signup': typeof AuthSignupRoute
  '/huddle/$channelId': typeof HuddleChannelIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/c/$channelId': typeof AppCChannelIdRoute
  '/dm/$channelId': typeof AppDmChannelIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/linear': typeof AppSettingsLinearRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/agents': typeof AppAgentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/departments/$departmentId/settings': typeof AppDepartmentsDepartmentIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/handovers': typeof AppHandoversRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/vault': typeof AppVaultRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/huddle/$channelId': typeof HuddleChannelIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/agents/new': typeof AppAgentsNewRoute
  '/_app/c/$channelId': typeof AppCChannelIdRoute
  '/_app/dm/$channelId': typeof AppDmChannelIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/linear': typeof AppSettingsLinearRoute
  '/_app/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/_app/departments/$departmentId/settings': typeof AppDepartmentsDepartmentIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/handovers'
    | '/members'
    | '/subscriptions'
    | '/tasks'
    | '/vault'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/huddle/$channelId'
    | '/agents/$agentId'
    | '/agents/new'
    | '/c/$channelId'
    | '/dm/$channelId'
    | '/projects/$projectId'
    | '/settings/company'
    | '/settings/linear'
    | '/settings/repositories'
    | '/invite/$token'
    | '/agents/'
    | '/projects/'
    | '/channels/$channelId/settings'
    | '/departments/$departmentId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handovers'
    | '/members'
    | '/subscriptions'
    | '/tasks'
    | '/vault'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/huddle/$channelId'
    | '/agents/$agentId'
    | '/agents/new'
    | '/c/$channelId'
    | '/dm/$channelId'
    | '/projects/$projectId'
    | '/settings/company'
    | '/settings/linear'
    | '/settings/repositories'
    | '/invite/$token'
    | '/agents'
    | '/projects'
    | '/channels/$channelId/settings'
    | '/departments/$departmentId/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/handovers'
    | '/_app/members'
    | '/_app/subscriptions'
    | '/_app/tasks'
    | '/_app/vault'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/signup'
    | '/huddle/$channelId'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/agents/new'
    | '/_app/c/$channelId'
    | '/_app/dm/$channelId'
    | '/_app/projects/$projectId'
    | '/_app/settings/company'
    | '/_app/settings/linear'
    | '/_app/settings/repositories'
    | '/_auth/invite/$token'
    | '/_app/agents/'
    | '/_app/projects/'
    | '/_app/channels/$channelId/settings'
    | '/_app/departments/$departmentId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  HuddleChannelIdRoute: typeof HuddleChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handovers': {
      id: '/_app/handovers'
      path: '/handovers'
      fullPath: '/handovers'
      preLoaderRoute: typeof AppHandoversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/huddle/$channelId': {
      id: '/huddle/$channelId'
      path: '/huddle/$channelId'
      fullPath: '/huddle/$channelId'
      preLoaderRoute: typeof HuddleChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/new': {
      id: '/_app/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AppAgentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$channelId': {
      id: '/_app/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof AppCChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/$channelId': {
      id: '/_app/dm/$channelId'
      path: '/dm/$channelId'
      fullPath: '/dm/$channelId'
      preLoaderRoute: typeof AppDmChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/linear': {
      id: '/_app/settings/linear'
      path: '/settings/linear'
      fullPath: '/settings/linear'
      preLoaderRoute: typeof AppSettingsLinearRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/repositories': {
      id: '/_app/settings/repositories'
      path: '/settings/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof AppSettingsRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/channels/$channelId/settings': {
      id: '/_app/channels/$channelId/settings'
      path: '/channels/$channelId/settings'
      fullPath: '/channels/$channelId/settings'
      preLoaderRoute: typeof AppChannelsChannelIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$departmentId/settings': {
      id: '/_app/departments/$departmentId/settings'
      path: '/departments/$departmentId/settings'
      fullPath: '/departments/$departmentId/settings'
      preLoaderRoute: typeof AppDepartmentsDepartmentIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHandoversRoute: typeof AppHandoversRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsNewRoute: typeof AppAgentsNewRoute
  AppCChannelIdRoute: typeof AppCChannelIdRoute
  AppDmChannelIdRoute: typeof AppDmChannelIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsLinearRoute: typeof AppSettingsLinearRoute
  AppSettingsRepositoriesRoute: typeof AppSettingsRepositoriesRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppChannelsChannelIdSettingsRoute: typeof AppChannelsChannelIdSettingsRoute
  AppDepartmentsDepartmentIdSettingsRoute: typeof AppDepartmentsDepartmentIdSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHandoversRoute: AppHandoversRoute,
  AppMembersRoute: AppMembersRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTasksRoute: AppTasksRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsNewRoute: AppAgentsNewRoute,
  AppCChannelIdRoute: AppCChannelIdRoute,
  AppDmChannelIdRoute: AppDmChannelIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsLinearRoute: AppSettingsLinearRoute,
  AppSettingsRepositoriesRoute: AppSettingsRepositoriesRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppChannelsChannelIdSettingsRoute: AppChannelsChannelIdSettingsRoute,
  AppDepartmentsDepartmentIdSettingsRoute:
    AppDepartmentsDepartmentIdSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  HuddleChannelIdRoute: HuddleChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
