/**
 * Service worker lifecycle for the installable app.
 *
 * `registerSW` (from `virtual:pwa-register`, generated by vite-plugin-pwa) installs
 * `src/sw.ts` and, with `registerType: 'autoUpdate'`, swaps in a new build as soon as
 * one is precached. The worker also posts `taut:navigate` when a notification is
 * clicked while a window is already open; we route it instead of reloading.
 */
import { registerSW } from 'virtual:pwa-register'

import { isDesktop } from '@/lib/desktop'

export interface PwaOptions {
  /** Called with an in-app path when a notification is clicked into an open window. */
  readonly onNavigate: (path: string) => void
}

/**
 * Idempotent: safe to call once at startup. No-ops where a service worker cannot run —
 * an insecure origin (a LAN `http://` instance), or the Electron shell, which does its
 * own OS notifications and badge counts and must not be pushed to twice.
 */
export const setupPwa = ({ onNavigate }: PwaOptions): void => {
  if (!('serviceWorker' in navigator) || !window.isSecureContext || isDesktop) return

  registerSW({ immediate: true })

  navigator.serviceWorker.addEventListener('message', (event) => {
    const data = event.data as { type?: string; url?: string } | null
    if (data === null || data.type !== 'taut:navigate') return
    // Only ever a same-origin path; the worker builds it from `location.origin`.
    if (typeof data.url === 'string' && data.url.startsWith('/')) onNavigate(data.url)
  })
}

/** True once a registration exists — push subscription needs one. */
export const serviceWorkerReady = async (): Promise<ServiceWorkerRegistration | undefined> => {
  if (!('serviceWorker' in navigator)) return undefined
  return await navigator.serviceWorker.ready
}
